version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - external_service
  external_service:
    image: python:3.9-slim
    command: python -m http.server 8080
    ports:
      - "8080:8080"
